# Generated by Django 3.2.2 on 2021-05-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['city'], 'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['name'], 'verbose_name': 'Авиакомпания', 'verbose_name_plural': 'Авиакомпании'},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'ordering': ['departure_time'], 'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['surename'], 'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='plane',
            options={'ordering': ['model_plane'], 'verbose_name': 'Самолёт', 'verbose_name_plural': 'Самолёты'},
        ),
        migrations.AlterModelOptions(
            name='tiket',
            options={'ordering': ['purchase_date'], 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RemoveField(
            model_name='plane',
            name='bussines_price',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='econom_price',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='trunk_sale',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='vip_price',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='window_upsale',
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default='Не указано', max_length=250, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='flights',
            name='bussines_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Стоимость бизнесс мест'),
        ),
        migrations.AddField(
            model_name='flights',
            name='econom_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость эконом мест'),
        ),
        migrations.AddField(
            model_name='flights',
            name='trunk_sale',
            field=models.IntegerField(default=0, verbose_name='Доплата за багаж'),
        ),
        migrations.AddField(
            model_name='flights',
            name='vip_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Стоимость vip мест'),
        ),
        migrations.AddField(
            model_name='flights',
            name='window_upsale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Доплата за место у окна'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='transfer_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_point', to='tikets.airport', verbose_name='Аэропорт пересадки'),
        ),
    ]
