# Generated by Django 3.1.3 on 2021-03-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id_airport', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('airport_name', models.CharField(max_length=250, verbose_name='Название аэропорта')),
                ('airport_code', models.CharField(max_length=10, verbose_name='Кодовое название аэропорта')),
                ('adress', models.CharField(max_length=1000, verbose_name='Адресс аэропорта')),
                ('contact_phone', models.IntegerField(verbose_name='Контактный телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id_carrier', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название компании')),
                ('contact_phone', models.IntegerField(verbose_name='Контактный номер перевозчика')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес регистрации')),
                ('logo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id_flights', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('arrival_point_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_point_airport', to='tikets.airport', verbose_name='Аэропорт назначения')),
                ('departure_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departure_airport', to='tikets.airport', verbose_name='Точка вылета')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surename', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('fathername', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('pasport', models.CharField(max_length=15, verbose_name='Серия/номер паспорта')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id_tiket', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(verbose_name='Номер места')),
                ('purchase_date', models.DateTimeField(auto_now=True, verbose_name='Дата покупки билета')),
                ('depatrure_date', models.DateTimeField(verbose_name='Дата вылета')),
                ('trunk', models.BooleanField(verbose_name='Наличие багажа')),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tikets.flights', verbose_name='Рейс')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tikets.order', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id_plane', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('model_plane', models.CharField(max_length=20, verbose_name='Модель самолёта')),
                ('places', models.IntegerField(verbose_name='Всего мест')),
                ('vip_places', models.IntegerField(blank=True, verbose_name='VIP мест')),
                ('vip_price', models.IntegerField(blank=True, verbose_name='Стоимость vip мест')),
                ('bussines_places', models.IntegerField(blank=True, verbose_name='Кол-во бизнесс мест')),
                ('bussines_price', models.IntegerField(blank=True, verbose_name='Стоимость бизнесс мест')),
                ('econom', models.IntegerField(verbose_name='Кол-во эконом мест')),
                ('econom_price', models.IntegerField(verbose_name='Стоимость эконом мест')),
                ('window_upsale', models.IntegerField(blank=True, verbose_name='Доплата за место у окна')),
                ('trunk_sale', models.IntegerField(verbose_name='Доплата за багаж')),
                ('carrier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tikets.carrier', verbose_name='Перевозчик')),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='plane_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tikets.plane', verbose_name='Самолёт'),
        ),
        migrations.AddField(
            model_name='flights',
            name='transfer_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_point', to='tikets.airport', verbose_name='Аэропорт пересадки'),
        ),
    ]
