# Generated by Django 3.1.3 on 2020-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201119_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
