# Generated by Django 3.1.3 on 2020-12-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_two_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Two',
        ),
    ]
